<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $cars = [
            // Economy / Student-friendly
            [
                'make'                => 'Renault',
                'model'               => 'Clio',
                'year'                => 2023,
                'category'            => 'economy',
                'price_per_day'       => 28.00,
                'seats'               => 5,
                'transmission'        => 'Manual',
                'fuel_type'           => 'Petrol',
                'status'              => 'available',
                'is_student_friendly' => true,
                'image_url'           => 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&q=80',
                'rating'              => 4.3,
                'reviews'             => 128,
                'color'               => 'Blanc Nacré',
                'license_plate'       => 'AB-123-CD',
                'mileage'             => 18500,
                'description'         => 'Parfaite citadine économique, idéale pour les trajets urbains.',
            ],
            [
                'make'                => 'Peugeot',
                'model'               => '208',
                'year'                => 2023,
                'category'            => 'economy',
                'price_per_day'       => 30.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Electric',
                'status'              => 'available',
                'is_student_friendly' => true,
                'image_url'           => 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80',
                'rating'              => 4.5,
                'reviews'             => 94,
                'color'               => 'Bleu Vertigo',
                'license_plate'       => 'EF-456-GH',
                'mileage'             => 9200,
                'description'         => 'Véhicule 100% électrique, zéro émission et silencieux.',
            ],
            [
                'make'                => 'Dacia',
                'model'               => 'Sandero',
                'year'                => 2022,
                'category'            => 'economy',
                'price_per_day'       => 22.00,
                'seats'               => 5,
                'transmission'        => 'Manual',
                'fuel_type'           => 'Petrol',
                'status'              => 'available',
                'is_student_friendly' => true,
                'image_url'           => 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&q=80',
                'rating'              => 4.1,
                'reviews'             => 302,
                'color'               => 'Gris Platine',
                'license_plate'       => 'IJ-789-KL',
                'mileage'             => 32000,
                'description'         => 'Le meilleur rapport qualité/prix du marché.',
            ],
            [
                'make'                => 'Citroën',
                'model'               => 'C3',
                'year'                => 2022,
                'category'            => 'economy',
                'price_per_day'       => 25.00,
                'seats'               => 5,
                'transmission'        => 'Manual',
                'fuel_type'           => 'Petrol',
                'status'              => 'available',
                'is_student_friendly' => true,
                'image_url'           => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80',
                'rating'              => 4.2,
                'reviews'             => 178,
                'color'               => 'Rouge Rubi',
                'license_plate'       => 'MN-012-OP',
                'mileage'             => 26500,
                'description'         => 'Confortable et polyvalente, parfaite pour la ville et la route.',
            ],
            [
                'make'                => 'Volkswagen',
                'model'               => 'Polo',
                'year'                => 2023,
                'category'            => 'economy',
                'price_per_day'       => 32.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Petrol',
                'status'              => 'available',
                'is_student_friendly' => true,
                'image_url'           => 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&q=80',
                'rating'              => 4.4,
                'reviews'             => 215,
                'color'               => 'Noir Intense',
                'license_plate'       => 'QR-345-ST',
                'mileage'             => 14200,
                'description'         => 'Fiabilité allemande à prix accessible.',
            ],

            // SUVs
            [
                'make'                => 'Toyota',
                'model'               => 'RAV4',
                'year'                => 2022,
                'category'            => 'suv',
                'price_per_day'       => 65.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Hybrid',
                'status'              => 'available',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80',
                'rating'              => 4.7,
                'reviews'             => 211,
                'color'               => 'Blanc Nacré',
                'license_plate'       => 'UV-678-WX',
                'mileage'             => 22000,
                'description'         => 'SUV hybride spacieux et économique, idéal pour la famille.',
            ],
            [
                'make'                => 'Mercedes',
                'model'               => 'GLE',
                'year'                => 2023,
                'category'            => 'suv',
                'price_per_day'       => 150.00,
                'seats'               => 7,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Diesel',
                'status'              => 'rented',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80',
                'rating'              => 4.8,
                'reviews'             => 45,
                'color'               => 'Gris Selenite',
                'license_plate'       => 'YZ-901-AB',
                'mileage'             => 8900,
                'description'         => 'SUV premium 7 places, confort et puissance exceptionnels.',
            ],
            [
                'make'                => 'Audi',
                'model'               => 'Q5',
                'year'                => 2023,
                'category'            => 'suv',
                'price_per_day'       => 95.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Hybrid',
                'status'              => 'available',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=600&q=80',
                'rating'              => 4.6,
                'reviews'             => 89,
                'color'               => 'Bleu Navarre',
                'license_plate'       => 'CD-234-EF',
                'mileage'             => 11200,
                'description'         => 'Le SUV premium par excellence, alliant technologie et confort.',
            ],
            [
                'make'                => 'Nissan',
                'model'               => 'Qashqai',
                'year'                => 2022,
                'category'            => 'suv',
                'price_per_day'       => 58.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Hybrid',
                'status'              => 'available',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=600&q=80',
                'rating'              => 4.4,
                'reviews'             => 143,
                'color'               => 'Vert Olive',
                'license_plate'       => 'GH-567-IJ',
                'mileage'             => 19800,
                'description'         => 'SUV compact polyvalent avec technologie e-Power.',
            ],

            // Luxury
            [
                'make'                => 'BMW',
                'model'               => '5 Series',
                'year'                => 2023,
                'category'            => 'luxury',
                'price_per_day'       => 120.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Petrol',
                'status'              => 'available',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80',
                'rating'              => 4.9,
                'reviews'             => 67,
                'color'               => 'Noir Saphir',
                'license_plate'       => 'KL-890-MN',
                'mileage'             => 6500,
                'description'         => 'Berline de luxe sportive, technologie de pointe BMW.',
            ],
            [
                'make'                => 'Mercedes',
                'model'               => 'Classe E',
                'year'                => 2023,
                'category'            => 'luxury',
                'price_per_day'       => 135.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Hybrid',
                'status'              => 'available',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=80',
                'rating'              => 4.8,
                'reviews'             => 52,
                'color'               => 'Argent Iridium',
                'license_plate'       => 'OP-123-QR',
                'mileage'             => 4200,
                'description'         => 'L\'élégance à l\'état pur avec une technologie MBUX avancée.',
            ],
            [
                'make'                => 'Porsche',
                'model'               => 'Cayenne',
                'year'                => 2023,
                'category'            => 'luxury',
                'price_per_day'       => 220.00,
                'seats'               => 5,
                'transmission'        => 'Automatic',
                'fuel_type'           => 'Hybrid',
                'status'              => 'maintenance',
                'is_student_friendly' => false,
                'image_url'           => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80',
                'rating'              => 5.0,
                'reviews'             => 28,
                'color'               => 'Rouge Carmine',
                'license_plate'       => 'ST-456-UV',
                'mileage'             => 3100,
                'description'         => 'SUV sportif de prestige — performance et raffinement.',
            ],
        ];

        foreach ($cars as $carData) {
            Car::create($carData);
        }

        $this->command->info('✅ Cars seeded: ' . count($cars) . ' records.');
    }
}
